// <auto-generated />
using System;
using AzShip.Infra.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzShip.Infra.Persistence.Migrations
{
    [DbContext(typeof(AzShipContext))]
    partial class AzShipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AzShip.Core.Models.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactEmail");

                    b.Property<string>("Description");

                    b.Property<string>("DestinationAddress");

                    b.Property<decimal>("Price");

                    b.Property<string>("SourceAddress");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });
#pragma warning restore 612, 618
        }
    }
}
